- name: SYNCTHING - Restart syncthing
  ansible.builtin.systemd:
    name: syncthing@{{ item }}
    state: restarted
    daemon_reload: yes
  with_items:
    - syncthing
    - syncthing-depl

- name: SYNCTHING - Restart syncthing on pulsemain
  ansible.builtin.systemd:
    name: syncthing@{{ item }}
    state: restarted
    daemon_reload: yes
  delegate_to: '{{ PULSEMAIN_IP }}'
  with_items:
    - syncthing
    - syncthing-depl

- name: SYNCTHING - Restart apache
  ansible.builtin.systemd:
    name: '{{ APACHE_DAEMON }}'
    state: restarted
    daemon_reload: yes

- name: SYNCTHING - Restart apache on pulsemain
  ansible.builtin.systemd:
    name: '{{ APACHE_DAEMON }}'
    state: restarted
    daemon_reload: yes
  delegate_to: '{{ PULSEMAIN_IP }}'
