- name: Set version for this playbook
  ansible.builtin.set_fact:
    ROLE_VERSION: '1.0.3'

- name: Display version
  ansible.builtin.debug:
    msg:
    - "{{role_name}} version: {{ ROLE_VERSION }}"

- name: GRAFANA - Stop service
  ansible.builtin.systemd:
    state: stopped
    name: grafana-server
  ignore_errors: true

- name: GRAFANA - Delete previous database
  ansible.builtin.file:
    path: /var/lib/grafana/grafana.db
    state: absent
