XMPP_DOMAIN: '{{ ansible_hostname }}'
XMPP_MASTER_PASSWORD: '' # 12 character string. Must be vaulted
SERVER_FQDN: '{{ ansible_fqdn }}'
INTERFACE: '{{ ansible_default_ipv4.interface }}'
IP_ADDRESS: "{{ vars['ansible_'~INTERFACE].ipv4.address }}"
# Define PUBLIC_IP if main pulse server also has a public relay. TODO: Maybe this needs to go in another task
PUBLIC_IP: ''
GUACAMOLE_ROOT_PASSWORD: '' # GUACAMOLE_ROOT_PASSWORD comes from guacamole role
GUACDBPASSWD: '{{ ROOT_PASSWORD }}'
CLIENTS_SSH_PORT: 22
CLIENTS_VNC_PORT: 5900
REVERSE_SSH_PORT: 22
ENTITY: Public
CLUSTER_NAME: '{{ ENTITY }}'
# For using database on another server, define DBHOST
DBHOST: localhost # To be set to PULSEMAIN_IP on relays
DBPORT: 3306
DBUSER: mmc
DBPASSWORD: '' # 12 character string. Must be vaulted
DBADMINUSER: root
DBADMINPASSWD: '{{ ROOT_PASSWORD }}'
PULSEMAIN_IP: '' # PULSEMAIN_IP must be set on relays
