##########################################################
#                 Syncthing Relay Server                 #
##########################################################

- name: STRELAYSRV - Install syncthing relay server
  ansible.builtin.apt:
    pkg:
      - syncthing-relaysrv
    state: latest
  when:
    - ansible_distribution == 'Debian'

- name: STRELAYSRV - Configure relay server
  ansible.builtin.copy:
    src: syncthing-relaysrv
    dest: /etc/default/
    mode: '0644'
  notify:
    - STRELAYSRV - Restart relay server
  when:
    - ansible_distribution == 'Debian'

- name: STRELAYSRV - Force restart of service after configuration
  ansible.builtin.meta: flush_handlers

- name: STRELAYSRV - Ensure syncthing relay server is running
  ansible.builtin.systemd:
    name: syncthing-relaysrv
    state: started
    enabled: yes
    masked: no
  when:
    - ansible_distribution == 'Debian'

- name: STRELAYSRV - Get Service Status
  ansible.builtin.shell: systemctl status syncthing-relaysrv.service |awk 'match($0, /.{7}-.{7}-.{7}-.{7}-.{7}-.{7}-.{7}-.{7}/) {print substr($0, RSTART, RLENGTH)}'
  register: strelaysrv_status
  when :
    - ansible_distribution == 'Debian'

- name: STRELAYSRV - Set STRELAYSRV_URL variable
  ansible.builtin.set_fact:
    STRELAYSRV_URL: relay://{{ SERVER_FQDN }}:22067/?id={{ strelaysrv_status.stdout }}
  when :
    - ansible_distribution == 'Debian'
    - strelaysrv_status.stdout != ""

- name: STRELAYSRV - Print STRELAYSRV_URL variable
  ansible.builtin.debug:
    var: STRELAYSRV_URL
  when:
    - ansible_distribution == 'Debian'
