- name: Reset medulla root password
  hosts: all
  remote_user: root
  serial: 1
  # environment: "{{ proxy_env }}"
  roles:
    - reset_medulla_password
  vars:
    # Make sure these vars are not defined elsewhere when running the playbook
    OLD_ROOT_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63313538643738356666343137656562333730376565323534373732633236383665373663383462
      3064363063343963373037326364396634643664343635360a623338656439303537643235646266
      36346236393131656439633264386265346166353938346264663130306333376638326134303337
      6137356136363631390a313766333139333962626266373333636639633163376339363063643030
      3266
    ROOT_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38316231633566346431373239373463616161316364326435653235376661383839343432376638
      6331346165313163626234326331363866326136616439660a656335333865643135336535633065
      64636461306234326631383639316133393530386134663362363965313830666464636263666130
      3935643139353563350a623936613038326331366265363266643965663835346366363562313433
      6338
