PULSE_BIOS_PATH: /var/lib/pulse2/imaging/bootloader
PULSE_UEFI32_PATH: /var/lib/pulse2/imaging/bootloader-uefi32
PULSE_UEFI64_PATH: /var/lib/pulse2/imaging/bootloader-uefi64
INTERFACE: '{{ ansible_default_ipv4.interface }}'
